name: CI Orders Service

on:
  push:
    branches: [ master ]

jobs:
  build:
    uses: cakes-management-system/ci-cd/.github/workflows/build-with-maven.yml@master
    with:
      display-name: Orders Service
      sonar: true
      sonar-project-key: cakes-management-system_orders-service
      publish: true
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
